### ISSUE TITLE
Properly research and set `ImOnline` related constants at runtime

### ISSUE THREAD

**Issue by dmitrylavrenov** [humanode-network/humanode#311]
As a follow up of #293

**Comment by MOZGIII** [comment]
Consts are sensible, and we've seen it working quite fine with the `libp2p` bug where nodes had a ton of addresses in the gossip; there is an issue with `ImOnline` that, I think, I've seen fixed in the later version of substrate (known to be past, say, `0.9.42`). After the fix, the max list sizes can be reduced significantly, but for now we kind of did good right away, as is anticipating that possible `libp2p` issue - not that specifically, but the general kind of troubles of this nature. Nice.
